branches:
  only:
    - master
    - /v\.\d+\.\d+\.\d+/
language: python
python: "2.7"
install:
  - pip install unittest2 mock pytype future git+https://github.com/romanvm/Kodistubs.git#egg=Kodistubs git+https://github.com/romanvm/kodi.six.git
script: pytype -V 2.7 ./script.module.pyxbmct/lib/pyxbmct/
script: python -m unittest2 discover
before_deploy:
  - pip install Sphinx
  - wget https://raw.githubusercontent.com/romanvm/travis_scripts/master/deploy_addon.py
  - python deploy_addon.py -z script.module.pyxbmct
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Publish docs to GH Pages
  - provider: script
    skip_cleanup: true
    script: python deploy_addon.py -d script.module.pyxbmct
  # Prepare for submitting to the official Kodi repo
  - provider: script
    skip_cleanup: true
    script: python deploy_addon.py -k repo-scripts -b leia script.module.pyxbmct
    on:
      tags: true
notifications:
  email: false