branches:
  only:
    - master
    - /\d+\.\d+\.\d+/
language: python
python: "3.6"
env:
  - ADDON_ID=script.module.pyxbmct
    BRANCH=leia
install:
  - pip install kodi-addon-checker
script:
  - kodi-addon-checker --branch $BRANCH $ADDON_ID
before_deploy:
  - pip install Sphinx six Kodistubs
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
deploy:
  # Submit to the official Kodi repo
  - provider: script
    skip_cleanup: true
    script: submit-addon -r repo-scrapers -b $BRANCH -s --pull-request $ADDON_ID
    on:
      tags: true
notifications:
  email: false
