language: python
env:
  - ADDON_ID=script.module.pyxbmct
    BRANCH=leia
matrix:
  include:
    - python: "2.7"
      install:
        - pip install ".[dev]"
      script:
        - pytype -V 2.7 ./script.module.pyxbmct/lib/pyxbmct/
        - python -m unittest2 discover
      before_deploy:
        - cd docs
        - make html
        - cd $TRAVIS_BUILD_DIR
      deploy:
        - provider: pages
          local-dir: docs/_build/html
          github-token: $GH_TOKEN
          skip_cleanup: true
          on:
            branch: master

    - python: "3.6"
      install:
        - pip install kodi-addon-checker
      script:
        - kodi-addon-checker --branch $BRANCH $ADDON_ID
      before_deploy:
        - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
      deploy:
        - provider: script
          script: submit-addon -r repo-scripts -b $BRANCH -s --pull-request $ADDON_ID
          on:
            tags: true
notifications:
  email: false
